name: online_exam_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  injectable: ^2.5.2
  # UI and Design
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  google_nav_bar: ^5.0.7
  cupertino_icons: ^1.0.8

  # Splash screen
  flutter_native_splash: ^2.4.7

  # State management
  flutter_bloc: ^9.1.1

  # navigation
  go_router: ^16.3.0

  # Dependency Injection
  get_it: ^8.2.0
 

  # API requests
  dio: ^5.9.0
  retrofit: ^4.8.0

  # JSON serialization
  json_annotation: ^4.9.0

  # Local storage
  shared_preferences: ^2.5.3

  # Lottie
  lottie: ^3.3.2
  equatable: ^2.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code generation tools
  build_runner: ^2.10.1
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  injectable_generator: ^2.9.1
  json_serializable: ^6.11.1
  retrofit_generator: ^10.1.1
  flutter_gen_runner: ^5.9.0
  pretty_dio_logger: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/


flutter_gen:
  output: lib/core/gen/
  integrations:
    lottie: true
    flutter_svg: true
